name: cicd

on:
 push:
  branches: 
  - master

jobs:
  build:
   runs-on: self-hosted
   
   steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: chmod +x build.sh
      - run: ./build.sh
      - run: |
         sudo systemctl stop tomcat9
         sudo rm -rf /var/lib/tomcat9/webapps/ROOT
         sudo rm -f /var/lib/tomcat9/webapps/ROOT.war
         sudo apt update
         sudo apt install tomcat9 -y
         sudo cp ROOT.war /var/lib/tomcat9/webapps/
         sudo systemctl restart tomcat9
